@Library("PTCSLibrary@1.2.0") _

// Podtemplate and node must match, dont use generic names like 'node', use more specific like projectname or node + excact version number.
// This is because CI environment reuses templates based on naming, if you create node 7 environment with name 'node', following node 8 environment
// builds may fail because they reuse same environment if label matches existing.
podTemplate(label: '<%= projectName %>',
  containers: [
    containerTemplate(name: 'node', image: 'node:8.9.1', ttyEnabled: true, command: '/bin/sh -c', args: 'cat'),
    containerTemplate(name: 'docker', image: 'ptcos/docker-client:1.1.32', alwaysPullImage: true, ttyEnabled: true, command: '/bin/sh -c', args: 'cat')
  ]
) {
    def project = '<%= projectName %>'
    def branch = (env.BRANCH_NAME)
    def namespace = "<%= namespace %>"
    def notifyslackchannel = "#jenkins"
    def notifymailrecipient = "forename.surname@protacon.com, forename.surname@protacon.com"

    node('<%= projectName %>') {
        try {
            // onStartNotifySlack(notifyslackchannel);
            // onStartNotifyEmail(notifymailrecipient);
            stage('Checkout') {
                checkout_with_tags()
            }
            stage('Build') {
                container('node') {
                    // sh """
                    //     npm install -g @angular/cli
                    //     npm install
                    //     ng build --prod
                    // """
                }
            }
            stage('Test') {
                container('node') {
                    // sh """
                    //     npm run test
                    // """
                }
            }
            stage('Package') {
                container('docker') {
                    def published = publishContainerToGcr(project, branch);

                    if(branch == "<%= branch %>") {
                        // This set DNS as public record, required on public traefiks,
                        // which means traefik ingresses with labels 'traefik-type: public'.
                        // This way ingress is exposed to public network needed. However this dns command is required for
                        // DNS work correctly with public traefik.
                        //
                        //setPublicDnsToK8sTestEnv("example-app-master.protacon.cloud")

                        // This replaces any matching image in testing environment with newest version.
                        applyToK8sTestEnv(published);

                        // In this body you have access to test environment with kubectl and gcloud tools against test project.
                        toK8sTestEnv {
                            sh "echo 'something here.'"
                        }
                    }
                }
            }
            // onSuccessNotifySlack(notifyslackchannel);
            // onSuccessNotifyEmail(notifymailrecipient);
        }
        catch (e) {
            currentBuild.result = "FAILED"
            // onFailureNotifySlack(notifyslackchannel);
            // onFailureNotifyEmail(notifymailrecipient);
            throw e
        }
    }
  }